### ISSUE TITLE
Organize the import order by using "@trivago/prettier-plugin-sort-imports"

### ISSUE THREAD

**Issue by tomo114883** [Litmus4883/docker-nestjs#41]
commit: https://github.com/Litmus4883/docker-nestjs/commit/b5d983ec86d8c4106112187fbcb644135034979c

**Comment by Litmus4883** [comment]
commit: https://github.com/Litmus4883/docker-nestjs/commit/b5d983ec86d8c4106112187fbcb644135034979c

**Comment by tomo114883** [comment]
commit: https://github.com/Litmus4883/docker-nestjs/commit/0d247320558252e09ed00db911916b36f6e32e07
